### ISSUE TITLE
README Typo

### ISSUE THREAD

**Issue by frederikdussault** [chenrui333/github-action-test#190]
Written

> I used to do something custom like https://github.com/chenrui333/github-action-test/pull/16, but [now it is native supproted](https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/).

Please correct "supproted" for "supported".

Thanks :)

**Comment by chenrui333** [comment]
Nice catch, fixing it now.
